sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t kai9702/travis_tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true kai9702/travis_tutorial npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "travis_tutorial"
  env: "TravisTutorial-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-950327587660"
  bucket_path: "travis_tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY